# Generated by Django 5.2.15 on 2026-06-22 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashboxes', '0006_sync_cashboxmovement_state'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='cashboxmovement',
            new_name='cashboxes_c_cashbox_c24814_idx',
            old_name='cashboxes_c_cashbox_f4d390_idx',
        ),
        migrations.RenameIndex(
            model_name='cashboxmovement',
            new_name='cashboxes_c_movemen_c3975c_idx',
            old_name='cashboxes_c_movemen_79f653_idx',
        ),
        migrations.RenameIndex(
            model_name='cashboxmovement',
            new_name='cashboxes_c_purchas_465a9c_idx',
            old_name='cashboxes_c_purchase_7b01da_idx',
        ),
        migrations.RenameIndex(
            model_name='cashboxmovement',
            new_name='cashboxes_c_sales_i_c908bb_idx',
            old_name='cashboxes_c_sales_i_3fdf45_idx',
        ),
        migrations.RenameIndex(
            model_name='cashboxmovement',
            new_name='cashboxes_c_supplie_5010be_idx',
            old_name='cashboxes_c_supplier_995d25_idx',
        ),
    ]
