# Generated by Django 5.2.17 on 2026-08-29 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashboxes', '0007_rename_cashboxes_c_cashbox_f4d390_idx_cashboxes_c_cashbox_c24814_idx_and_more'),
        ('master_data', '0001_initial'),
        ('purchases', '0004_rename_purchases_p_invoice_8b5be9_idx_purchases_p_invoice_1e2224_idx_and_more'),
        ('sales', '0007_sync_sales_model_state'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OpeningBalanceAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_number', models.CharField(max_length=100, unique=True)),
                ('target_type', models.CharField(choices=[('customer', 'Customer'), ('supplier', 'Supplier'), ('cashbox', 'Cashbox')], max_length=20)),
                ('adjustment_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('posted', 'Posted'), ('cancelled', 'Cancelled')], default='posted', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('reversal_date', models.DateField(blank=True, null=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancelled_opening_balance_adjustments', to=settings.AUTH_USER_MODEL)),
                ('cashbox', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='opening_balance_adjustments', to='cashboxes.cashbox')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_opening_balance_adjustments', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='opening_balance_adjustments', to='master_data.customer')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='opening_balance_adjustments', to='master_data.supplier')),
            ],
            options={
                'ordering': ['-adjustment_date', '-id'],
            },
        ),
        migrations.AddField(
            model_name='cashboxmovement',
            name='opening_balance_adjustment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cashbox_movements', to='cashboxes.openingbalanceadjustment'),
        ),
        migrations.AddIndex(
            model_name='cashboxmovement',
            index=models.Index(fields=['opening_balance_adjustment'], name='cashboxes_c_opening_d6347e_idx'),
        ),
        migrations.AddIndex(
            model_name='openingbalanceadjustment',
            index=models.Index(fields=['target_type', 'status'], name='cashboxes_o_target__0e75be_idx'),
        ),
        migrations.AddIndex(
            model_name='openingbalanceadjustment',
            index=models.Index(fields=['adjustment_date'], name='cashboxes_o_adjustm_07a0e9_idx'),
        ),
        migrations.AddIndex(
            model_name='openingbalanceadjustment',
            index=models.Index(fields=['customer'], name='cashboxes_o_custome_7658f0_idx'),
        ),
        migrations.AddIndex(
            model_name='openingbalanceadjustment',
            index=models.Index(fields=['supplier'], name='cashboxes_o_supplie_24b9e3_idx'),
        ),
        migrations.AddIndex(
            model_name='openingbalanceadjustment',
            index=models.Index(fields=['cashbox'], name='cashboxes_o_cashbox_4cec6c_idx'),
        ),
    ]
