# Generated by Django 5.2.17 on 2026-08-29 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashboxes', '0008_openingbalanceadjustment_and_more'),
        ('purchases', '0005_supplierledgerentry_opening_balance_adjustment_and_more'),
        ('sales', '0008_customerledgerentry_opening_balance_adjustment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cashboxmovement',
            name='reversal_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal_movements', to='cashboxes.cashboxmovement'),
        ),
        migrations.CreateModel(
            name='CashboxOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(max_length=100, unique=True)),
                ('operation_date', models.DateField()),
                ('operation_type', models.CharField(choices=[('direct_in', 'Direct cash in'), ('direct_out', 'Direct cash out'), ('transfer', 'Cashbox transfer')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('posted', 'Posted'), ('cancelled', 'Cancelled')], default='posted', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('reversal_date', models.DateField(blank=True, null=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancelled_cashbox_operations', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_cashbox_operations', to=settings.AUTH_USER_MODEL)),
                ('destination_cashbox', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_operations_in', to='cashboxes.cashbox')),
                ('source_cashbox', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_operations_out', to='cashboxes.cashbox')),
            ],
            options={
                'ordering': ['-operation_date', '-id'],
            },
        ),
        migrations.AddField(
            model_name='cashboxmovement',
            name='cashbox_operation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='cashboxes.cashboxoperation'),
        ),
        migrations.AddIndex(
            model_name='cashboxmovement',
            index=models.Index(fields=['cashbox_operation'], name='cashboxes_c_cashbox_9c45de_idx'),
        ),
        migrations.AddIndex(
            model_name='cashboxmovement',
            index=models.Index(fields=['reversal_of'], name='cashboxes_c_reversa_b94697_idx'),
        ),
        migrations.AddIndex(
            model_name='cashboxoperation',
            index=models.Index(fields=['operation_type', 'status'], name='cashboxes_c_operati_b42aff_idx'),
        ),
        migrations.AddIndex(
            model_name='cashboxoperation',
            index=models.Index(fields=['operation_date'], name='cashboxes_c_operati_030b9f_idx'),
        ),
        migrations.AddIndex(
            model_name='cashboxoperation',
            index=models.Index(fields=['source_cashbox'], name='cashboxes_c_source__9bb1f4_idx'),
        ),
        migrations.AddIndex(
            model_name='cashboxoperation',
            index=models.Index(fields=['destination_cashbox'], name='cashboxes_c_destina_570173_idx'),
        ),
    ]
