# Generated by Django 5.2.17 on 2026-08-29 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashboxes', '0009_cashboxmovement_reversal_of_cashboxoperation_and_more'),
        ('purchases', '0006_purchasereturnline_purchasereturn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashboxmovement',
            name='purchase_return',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cashbox_movements', to='purchases.purchasereturn'),
        ),
    ]
