# Generated by Django 5.2.17 on 2026-08-29 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashboxes', '0010_cashboxmovement_purchase_return'),
        ('purchases', '0006_purchasereturnline_purchasereturn_and_more'),
        ('sales', '0009_salesreturnline_salesreturn_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cashboxmovement',
            name='sales_return',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cashbox_movements', to='sales.salesreturn'),
        ),
        migrations.AlterField(
            model_name='cashboxmovement',
            name='movement_type',
            field=models.CharField(choices=[('purchase_payment', 'Purchase payment'), ('sales_receipt', 'Sales receipt'), ('supplier_payment', 'Supplier payment'), ('customer_payment', 'Customer payment'), ('purchase_return', 'Purchase return refund'), ('sales_return', 'Sales return refund'), ('direct_in', 'Direct in'), ('direct_out', 'Direct out'), ('transfer_in', 'Transfer in'), ('transfer_out', 'Transfer out'), ('adjustment', 'Adjustment')], max_length=40),
        ),
        migrations.AddIndex(
            model_name='cashboxmovement',
            index=models.Index(fields=['purchase_return'], name='cashboxes_c_purchas_65886e_idx'),
        ),
        migrations.AddIndex(
            model_name='cashboxmovement',
            index=models.Index(fields=['sales_return'], name='cashboxes_c_sales_r_158ebe_idx'),
        ),
    ]
