# Generated by Django 5.2.17 on 2026-10-05 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cashboxes", "0012_cashbox_entity"),
        ("entities", "0001_initial"),
        ("ledger", "0001_initial"),
        ("master_data", "0002_location_entity"),
    ]

    operations = [
        migrations.CreateModel(
            name="JournalEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entry_date", models.DateField(db_index=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("projected", "From a document"),
                            ("manual", "Manual"),
                        ],
                        default="projected",
                        max_length=20,
                    ),
                ),
                ("source_type", models.CharField(db_index=True, max_length=40)),
                ("source_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("reference", models.CharField(blank=True, max_length=100)),
                ("memo", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["entry_date", "pk"],
                "indexes": [
                    models.Index(
                        fields=["source_type", "source_id"],
                        name="ledger_jour_source__23ab73_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="JournalLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "debit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                (
                    "credit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                ("memo", models.CharField(blank=True, max_length=255)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lines",
                        to="ledger.account",
                    ),
                ),
                (
                    "cashbox",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="cashboxes.cashbox",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="master_data.customer",
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="journal_lines",
                        to="entities.entity",
                    ),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="ledger.journalentry",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="master_data.location",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="master_data.supplier",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["account", "entity"],
                        name="ledger_jour_account_83289a_idx",
                    )
                ],
            },
        ),
    ]
