# Generated by Django 5.2.17 on 2026-09-27 10:42

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("master_data", "0001_initial"),
        ("sales", "0009_salesreturnline_salesreturn_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaxRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name_ar", models.CharField(max_length=120)),
                ("name_en", models.CharField(blank=True, max_length=120)),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                    ),
                ),
                ("eta_type", models.CharField(blank=True, default="T1", max_length=8)),
                ("eta_subtype", models.CharField(blank=True, max_length=8)),
                ("is_default", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-is_default", "code"],
            },
        ),
        migrations.CreateModel(
            name="SalesReturnLineTax",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tax_amount", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "return_line",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tax",
                        to="sales.salesreturnline",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SalesLineTax",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rate", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "taxable_amount",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                ("tax_amount", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "line",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tax",
                        to="sales.salesline",
                    ),
                ),
                (
                    "tax_rate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="taxes.taxrate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ItemTaxRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tax_rate_link",
                        to="master_data.item",
                    ),
                ),
                (
                    "tax_rate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="taxes.taxrate",
                    ),
                ),
            ],
        ),
    ]
