# Generated by Django 5.2.17 on 2026-09-27 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchases", "0006_purchasereturnline_purchasereturn_and_more"),
        ("taxes", "0002_seed_rates"),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseLineTax",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rate", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "taxable_amount",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                ("tax_amount", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "line",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tax",
                        to="purchases.purchaseline",
                    ),
                ),
                (
                    "tax_rate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="taxes.taxrate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PurchaseReturnLineTax",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tax_amount", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "return_line",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tax",
                        to="purchases.purchasereturnline",
                    ),
                ),
            ],
        ),
    ]
