# Generated by Django 5.2.17 on 2026-09-27 17:17

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("master_data", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_ar", models.CharField(max_length=60)),
                ("name_en", models.CharField(blank=True, max_length=60)),
                (
                    "factor",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="How many base units one of these holds, e.g. 12 pieces in a carton.",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("1.001"))
                        ],
                    ),
                ),
                (
                    "barcode",
                    models.CharField(blank=True, db_index=True, max_length=120),
                ),
                (
                    "sale_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "purchase_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alt_units",
                        to="master_data.item",
                    ),
                ),
            ],
            options={
                "ordering": ["item_id", "factor"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("item", "name_ar"), name="units_one_name_per_item"
                    )
                ],
            },
        ),
    ]
