# Generated by Django 5.2.17 on 2026-10-08 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("message", models.TextField()),
                (
                    "mood",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("great", "great"),
                            ("good", "good"),
                            ("meh", "meh"),
                            ("bad", "bad"),
                        ],
                        max_length=10,
                    ),
                ),
                ("contact", models.CharField(blank=True, max_length=120)),
                ("path", models.CharField(blank=True, max_length=500)),
                ("lang", models.CharField(blank=True, max_length=5)),
                ("activity", models.CharField(blank=True, max_length=40)),
                ("sub_activity", models.CharField(blank=True, max_length=40)),
                ("role", models.CharField(blank=True, max_length=40)),
                ("sandbox", models.CharField(blank=True, db_index=True, max_length=64)),
                ("viewport", models.CharField(blank=True, max_length=20)),
                ("user_agent", models.CharField(blank=True, max_length=300)),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
