# Generated by Django 5.2.17 on 2026-10-10 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Visit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("visitor", models.CharField(max_length=64, unique=True)),
                ("sandbox", models.CharField(blank=True, db_index=True, max_length=64)),
                ("started_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("last_seen_at", models.DateTimeField(db_index=True)),
                ("name", models.CharField(blank=True, max_length=120)),
                ("phone", models.CharField(blank=True, max_length=40)),
                ("activity", models.CharField(blank=True, max_length=40)),
                ("sub_activity", models.CharField(blank=True, max_length=40)),
                ("role", models.CharField(blank=True, max_length=40)),
                ("pages", models.PositiveIntegerField(default=0)),
                ("first_path", models.CharField(blank=True, max_length=500)),
                ("last_path", models.CharField(blank=True, max_length=500)),
                ("lang", models.CharField(blank=True, max_length=5)),
                ("user_agent", models.CharField(blank=True, max_length=300)),
            ],
            options={
                "ordering": ["-last_seen_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PageView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("path", models.CharField(max_length=500)),
                ("activity", models.CharField(blank=True, max_length=40)),
                ("sub_activity", models.CharField(blank=True, max_length=40)),
                (
                    "visit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="views",
                        to="feedback.visit",
                    ),
                ),
            ],
            options={
                "ordering": ["at", "id"],
            },
        ),
    ]
