# Generated by Django 5.2.15 on 2026-06-22 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_supplierpayment'),
    ]

    operations = [
        migrations.RenameIndex(model_name='purchaseinvoice', new_name='purchases_p_invoice_1e2224_idx', old_name='purchases_p_invoice_8b5be9_idx'),
        migrations.RenameIndex(model_name='purchaseinvoice', new_name='purchases_p_invoice_5459cf_idx', old_name='purchases_p_invoice_b1f6aa_idx'),
        migrations.RenameIndex(model_name='purchaseinvoice', new_name='purchases_p_supplie_0c2d47_idx', old_name='purchases_p_supplier_574e15_idx'),
        migrations.RenameIndex(model_name='purchaseinvoice', new_name='purchases_p_status_d20e7f_idx', old_name='purchases_p_status_6308f7_idx'),
        migrations.RenameIndex(model_name='purchaseline', new_name='purchases_p_invoice_266aea_idx', old_name='purchases_p_invoice_c17104_idx'),
        migrations.RenameIndex(model_name='purchaseline', new_name='purchases_p_item_id_e85158_idx', old_name='purchases_p_item_id_4759ec_idx'),
        migrations.RenameIndex(model_name='supplierledgerentry', new_name='purchases_s_supplie_c7f1e1_idx', old_name='purchases_s_supplier_379c60_idx'),
        migrations.RenameIndex(model_name='supplierledgerentry', new_name='purchases_s_entry_t_314878_idx', old_name='purchases_s_entry_t_2d5b56_idx'),
        migrations.RenameIndex(model_name='supplierledgerentry', new_name='purchases_s_purchas_8f0f56_idx', old_name='purchases_s_purchase_0e66da_idx'),
        migrations.RenameIndex(model_name='supplierledgerentry', new_name='purchases_s_supplie_9babd4_idx', old_name='purchases_s_supplier_64cc03_idx'),
        migrations.RenameIndex(model_name='supplierpayment', new_name='purchases_s_payment_9fd54a_idx', old_name='purchases_s_payment_9c31a0_idx'),
        migrations.RenameIndex(model_name='supplierpayment', new_name='purchases_s_payment_41eef4_idx', old_name='purchases_s_payment_6f2f10_idx'),
        migrations.RenameIndex(model_name='supplierpayment', new_name='purchases_s_supplie_ce2a5c_idx', old_name='purchases_s_supplier_a9bf19_idx'),
        migrations.RenameIndex(model_name='supplierpayment', new_name='purchases_s_cashbox_194222_idx', old_name='purchases_s_cashbox_e86b6b_idx'),
        migrations.RenameIndex(model_name='supplierpayment', new_name='purchases_s_status_7cb5fe_idx', old_name='purchases_s_status_e5c0c4_idx'),
    ]
