# Generated by Django 5.2.17 on 2026-08-29 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashboxes', '0008_openingbalanceadjustment_and_more'),
        ('master_data', '0001_initial'),
        ('purchases', '0004_rename_purchases_p_invoice_8b5be9_idx_purchases_p_invoice_1e2224_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierledgerentry',
            name='opening_balance_adjustment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_ledger_entries', to='cashboxes.openingbalanceadjustment'),
        ),
        migrations.AddIndex(
            model_name='supplierledgerentry',
            index=models.Index(fields=['opening_balance_adjustment'], name='purchases_s_opening_4d9dc1_idx'),
        ),
    ]
