# Generated by Django 5.2.17 on 2026-08-29 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashboxes', '0009_cashboxmovement_reversal_of_cashboxoperation_and_more'),
        ('master_data', '0001_initial'),
        ('purchases', '0005_supplierledgerentry_opening_balance_adjustment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseReturnLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('unit_cost', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
            ],
            options={
                'ordering': ['purchase_return', 'source_line__line_number'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_number', models.CharField(max_length=80, unique=True)),
                ('return_date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cash_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('due_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('posted', 'Posted'), ('cancelled', 'Cancelled')], default='posted', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('reversal_date', models.DateField(blank=True, null=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancelled_purchase_returns', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_purchase_returns', to=settings.AUTH_USER_MODEL)),
                ('source_invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='purchases.purchaseinvoice')),
            ],
            options={
                'ordering': ['-return_date', '-id'],
            },
        ),
        migrations.AddField(
            model_name='supplierledgerentry',
            name='purchase_return',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_ledger_entries', to='purchases.purchasereturn'),
        ),
        migrations.AddIndex(
            model_name='supplierledgerentry',
            index=models.Index(fields=['purchase_return'], name='purchases_s_purchas_7f5918_idx'),
        ),
        migrations.AddField(
            model_name='purchasereturnline',
            name='purchase_return',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='purchases.purchasereturn'),
        ),
        migrations.AddField(
            model_name='purchasereturnline',
            name='source_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_lines', to='purchases.purchaseline'),
        ),
        migrations.AddIndex(
            model_name='purchasereturn',
            index=models.Index(fields=['return_number'], name='purchases_p_return__2a5ffc_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasereturn',
            index=models.Index(fields=['return_date'], name='purchases_p_return__6f2f93_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasereturn',
            index=models.Index(fields=['source_invoice', 'status'], name='purchases_p_source__a84d92_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasereturnline',
            index=models.Index(fields=['source_line'], name='purchases_p_source__70d8f3_idx'),
        ),
        migrations.AddConstraint(
            model_name='purchasereturnline',
            constraint=models.UniqueConstraint(fields=('purchase_return', 'source_line'), name='unique_purchase_return_source_line'),
        ),
    ]
