# Generated by Django 5.2.15 on 2026-06-22 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0003_import_status_choices_and_options'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='importbatch',
            new_name='imports_imp_batch_c_e65609_idx',
            old_name='imports_bat_batch_c_2c84dd_idx',
        ),
        migrations.RenameIndex(
            model_name='importbatch',
            new_name='imports_imp_target__c3a8ce_idx',
            old_name='imports_bat_target__9cd011_idx',
        ),
        migrations.RenameIndex(
            model_name='importbatch',
            new_name='imports_imp_go_live_6feae3_idx',
            old_name='imports_bat_go_live_537a3e_idx',
        ),
        migrations.RenameIndex(
            model_name='importraw',
            new_name='imports_imp_batch_i_370701_idx',
            old_name='imports_raw_batch_i_5395f3_idx',
        ),
        migrations.RenameIndex(
            model_name='importraw',
            new_name='imports_imp_target__a486e3_idx',
            old_name='imports_raw_target__fa5a65_idx',
        ),
        migrations.RenameIndex(
            model_name='importreview',
            new_name='imports_imp_batch_i_5f8a7b_idx',
            old_name='imports_rev_batch_i_5c7f87_idx',
        ),
        migrations.RenameIndex(
            model_name='importreview',
            new_name='imports_imp_raw_row_8f1a17_idx',
            old_name='imports_rev_raw_row_02f66e_idx',
        ),
    ]
