# Generated by Django 5.2.17 on 2026-09-28 21:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sales", "0009_salesreturnline_salesreturn_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OfflineSale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sale_key", models.UUIDField(unique=True)),
                (
                    "recorded_at",
                    models.DateTimeField(
                        help_text="When the cashier rang it up on the device."
                    ),
                ),
                ("synced_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cashier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="offline_sales",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invoice",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="offline_sale",
                        to="sales.salesinvoice",
                    ),
                ),
            ],
            options={
                "ordering": ["-synced_at"],
            },
        ),
    ]
