# Generated by Django 5.2.15 on 2026-06-22 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings_core', '0004_usage_index_names'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='usagestatussnapshot',
            new_name='settings_co_created_ddac57_idx',
            old_name='settings_co_created_0ddac57_idx',
        ),
    ]
