# Generated by Django 5.2.17 on 2026-08-20 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_core', '0005_rename_settings_co_created_0ddac57_idx_settings_co_created_ddac57_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='activity_slug',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='setup_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='sub_activity_slug',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
