# Generated by Django 5.2.17 on 2026-09-28 01:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cashboxes", "0011_cashboxmovement_sales_return_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Shift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Open"), ("closed", "Closed")],
                        default="open",
                        max_length=10,
                    ),
                ),
                ("opened_at", models.DateTimeField()),
                ("opening_float", models.DecimalField(decimal_places=2, max_digits=14)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "expected_cash",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "counted_cash",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "difference",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("summary", models.JSONField(blank=True, default=dict)),
                ("notes", models.CharField(blank=True, max_length=255)),
                (
                    "cashbox",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shifts",
                        to="cashboxes.cashbox",
                    ),
                ),
                (
                    "cashier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shifts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "difference_operation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="cashboxes.cashboxoperation",
                    ),
                ),
            ],
            options={
                "ordering": ["-opened_at", "-pk"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "open")),
                        fields=("cashier",),
                        name="shifts_one_open_per_cashier",
                    )
                ],
            },
        ),
    ]
