# Generated by Django 5.2.17 on 2026-08-29 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_stockmovement_created_at'),
        ('master_data', '0001_initial'),
        ('purchases', '0005_supplierledgerentry_opening_balance_adjustment_and_more'),
        ('sales', '0008_customerledgerentry_opening_balance_adjustment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='reversal_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal_movements', to='inventory.stockmovement'),
        ),
        migrations.CreateModel(
            name='StockOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(max_length=100, unique=True)),
                ('operation_date', models.DateField()),
                ('operation_type', models.CharField(choices=[('transfer', 'Transfer'), ('adjustment', 'Adjustment')], max_length=20)),
                ('adjustment_direction', models.CharField(blank=True, choices=[('in', 'Increase'), ('out', 'Decrease')], max_length=10)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('unit_cost', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('posted', 'Posted'), ('cancelled', 'Cancelled')], default='posted', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('reversal_date', models.DateField(blank=True, null=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancelled_stock_operations', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_stock_operations', to=settings.AUTH_USER_MODEL)),
                ('destination_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_operations_in', to='master_data.location')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_operations', to='master_data.item')),
                ('source_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_operations_out', to='master_data.location')),
            ],
            options={
                'ordering': ['-operation_date', '-id'],
            },
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='stock_operation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.stockoperation'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['stock_operation'], name='inventory_s_stock_o_8b4d1c_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['reversal_of'], name='inventory_s_reversa_fa4789_idx'),
        ),
        migrations.AddIndex(
            model_name='stockoperation',
            index=models.Index(fields=['operation_type', 'status'], name='inventory_s_operati_223b1f_idx'),
        ),
        migrations.AddIndex(
            model_name='stockoperation',
            index=models.Index(fields=['operation_date'], name='inventory_s_operati_6facbd_idx'),
        ),
        migrations.AddIndex(
            model_name='stockoperation',
            index=models.Index(fields=['item'], name='inventory_s_item_id_0f27f3_idx'),
        ),
    ]
