# Generated by Django 5.2.17 on 2026-08-29 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_stockmovement_reversal_of_stockoperation_and_more'),
        ('purchases', '0006_purchasereturnline_purchasereturn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='purchase_return',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='purchases.purchasereturn'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='purchase_return_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='purchases.purchasereturnline'),
        ),
    ]
