# Generated by Django 5.2.17 on 2026-08-29 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_stockmovement_purchase_return_and_more'),
        ('master_data', '0001_initial'),
        ('purchases', '0006_purchasereturnline_purchasereturn_and_more'),
        ('sales', '0009_salesreturnline_salesreturn_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='sales_return',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='sales.salesreturn'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='sales_return_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='sales.salesreturnline'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['purchase_return'], name='inventory_s_purchas_e0298f_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['purchase_return_line'], name='inventory_s_purchas_04e782_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['sales_return'], name='inventory_s_sales_r_50557f_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['sales_return_line'], name='inventory_s_sales_r_d01d6a_idx'),
        ),
    ]
