# Generated by Django 5.2.17 on 2026-10-09 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0006_stockmovement_sales_return_and_more"),
        ("master_data", "0003_sales_rep"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TransferRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=30, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("sent", "Sent"),
                            ("received", "Received"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="requested",
                        max_length=20,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=255)),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("received_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancel_reason", models.CharField(blank=True, max_length=255)),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfer_requests_in",
                        to="master_data.location",
                    ),
                ),
                (
                    "received_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sent_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfer_requests_out",
                        to="master_data.location",
                    ),
                ),
            ],
            options={
                "ordering": ["-requested_at", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="LocationStockLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "min_quantity",
                    models.DecimalField(decimal_places=3, default=0, max_digits=14),
                ),
                (
                    "max_quantity",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        help_text="0 = no ceiling.",
                        max_digits=14,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="location_levels",
                        to="master_data.item",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_levels",
                        to="master_data.location",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["location_id", "item_id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("location", "item"),
                        name="inv_one_level_per_location_item",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TransferRequestLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "requested_quantity",
                    models.DecimalField(decimal_places=3, max_digits=14),
                ),
                (
                    "sent_quantity",
                    models.DecimalField(decimal_places=3, default=0, max_digits=14),
                ),
                (
                    "received_quantity",
                    models.DecimalField(decimal_places=3, default=0, max_digits=14),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="master_data.item",
                    ),
                ),
                (
                    "loss_operation",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfer_request_loss",
                        to="inventory.stockoperation",
                    ),
                ),
                (
                    "receive_operation",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfer_request_receive",
                        to="inventory.stockoperation",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="inventory.transferrequest",
                    ),
                ),
                (
                    "send_operation",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfer_request_send",
                        to="inventory.stockoperation",
                    ),
                ),
            ],
            options={
                "ordering": ["pk"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("request", "item"), name="inv_one_request_line_per_item"
                    )
                ],
            },
        ),
    ]
