# Generated by Django 5.2.17 on 2026-10-11 00:11

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("entities", "0001_initial"),
        ("master_data", "0003_sales_rep"),
        ("staff", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                (
                    "basis",
                    models.CharField(
                        choices=[
                            ("monthly", "Monthly"),
                            ("course", "Whole course"),
                            ("session", "Per session"),
                        ],
                        default="monthly",
                        max_length=10,
                    ),
                ),
                (
                    "fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "entity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="entities.entity",
                    ),
                ),
                (
                    "item",
                    models.OneToOneField(
                        help_text="The service line its invoices use.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="course",
                        to="master_data.item",
                    ),
                ),
            ],
            options={
                "ordering": ["name", "pk"],
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "stage",
                    models.CharField(
                        blank=True,
                        help_text="Grade, level or age group.",
                        max_length=80,
                    ),
                ),
                ("school", models.CharField(blank=True, max_length=120)),
                (
                    "relation",
                    models.CharField(
                        blank=True,
                        help_text="The payer's relation to the student: father, mother, self…",
                        max_length=40,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="entities.entity",
                    ),
                ),
                (
                    "payer",
                    models.ForeignKey(
                        help_text="Who pays and holds the account: a parent, or the student.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="students",
                        to="master_data.customer",
                    ),
                ),
            ],
            options={
                "ordering": ["name", "pk"],
            },
        ),
        migrations.CreateModel(
            name="StudyGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=160)),
                ("room", models.CharField(blank=True, max_length=60)),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        default=0, help_text="0 means no limit."
                    ),
                ),
                (
                    "days",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated weekdays, e.g. sat,mon,wed.",
                        max_length=40,
                    ),
                ),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("duration_minutes", models.PositiveIntegerField(default=60)),
                (
                    "fee",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Blank: the course's fee.",
                        max_digits=12,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                ("starts_on", models.DateField(blank=True, null=True)),
                ("ends_on", models.DateField(blank=True, null=True)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="groups",
                        to="education.course",
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="entities.entity",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="study_groups",
                        to="staff.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["course__name", "name", "pk"],
            },
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "discount_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Siblings, scholarships…",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("stopped", "Stopped")],
                        db_index=True,
                        default="active",
                        max_length=10,
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enrollments",
                        to="education.student",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enrollments",
                        to="education.studygroup",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date", "-pk"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "active")),
                        fields=("student", "group"),
                        name="education_one_active_enrollment_per_group",
                    )
                ],
            },
        ),
    ]
