# Generated by Django 5.2.17 on 2026-10-11 00:01

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("education", "0002_classsession_attendance_and_more"),
        ("sales", "0010_sales_rep"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeeCharge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "month",
                    models.DateField(help_text="The first day of the month billed."),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1"),
                        help_text="Months, or classes attended for per-class fees.",
                        max_digits=8,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="charges",
                        to="education.enrollment",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fee_charges",
                        to="sales.salesinvoice",
                    ),
                ),
            ],
            options={
                "ordering": ["-month", "pk"],
                "indexes": [
                    models.Index(
                        fields=["enrollment", "month"],
                        name="education_f_enrollm_1daa0e_idx",
                    )
                ],
            },
        ),
    ]
