# Generated by Django 5.2.17 on 2026-09-27 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("master_data", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code_type",
                    models.CharField(
                        choices=[
                            ("EGS", "EGS (internal code registered with ETA)"),
                            ("GS1", "GS1 (international barcode)"),
                        ],
                        default="EGS",
                        max_length=3,
                    ),
                ),
                ("code", models.CharField(max_length=100)),
                ("unit_type", models.CharField(default="EA", max_length=10)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="einvoice_code",
                        to="master_data.item",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReceiverProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "receiver_type",
                    models.CharField(
                        choices=[
                            ("B", "Business in Egypt"),
                            ("P", "Natural person"),
                            ("F", "Foreigner"),
                        ],
                        default="P",
                        max_length=1,
                    ),
                ),
                (
                    "tax_id",
                    models.CharField(
                        blank=True,
                        help_text="Tax registration number (B), national ID (P) or passport / foreign ID (F).",
                        max_length=30,
                    ),
                ),
                ("country", models.CharField(default="EG", max_length=2)),
                ("governate", models.CharField(blank=True, max_length=100)),
                ("region_city", models.CharField(blank=True, max_length=100)),
                ("street", models.CharField(blank=True, max_length=200)),
                ("building_number", models.CharField(blank=True, max_length=50)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="einvoice_profile",
                        to="master_data.customer",
                    ),
                ),
            ],
        ),
    ]
