# Generated by Django 5.2.17 on 2026-10-09 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0006_stockmovement_sales_return_and_more"),
        ("manufacturing", "0002_productionorder_orderstagelog"),
    ]

    operations = [
        migrations.AddField(
            model_name="productionrun",
            name="conversion_cost",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name="productionrun",
            name="scrap_quantity",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14),
        ),
        migrations.CreateModel(
            name="OrderMaterialIssue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "operation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_issue",
                        to="inventory.stockoperation",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issues",
                        to="manufacturing.productionorder",
                    ),
                ),
            ],
            options={
                "ordering": ["pk"],
            },
        ),
    ]
