# Generated by Django 5.2.15 on 2026-06-22 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_audit_created_2c1626_idx',
            old_name='audit_audit_created_87df99_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_audit_event_t_4496ba_idx',
            old_name='audit_audit_event_t_5faf23_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_audit_module_365bd8_idx',
            old_name='audit_audit_module_4edb99_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_audit_object__1f9df3_idx',
            old_name='audit_audit_object__21cba8_idx',
        ),
    ]
