# Generated by Django 5.2.15 on 2026-06-22 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closing', '0007_adjustment_indexes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='closingrun',
            options={'ordering': ['-started_at', '-id'], 'verbose_name': 'Closing Run', 'verbose_name_plural': 'Closing Runs'},
        ),
        migrations.AlterModelOptions(
            name='period',
            options={'ordering': ['-start_date', '-id'], 'verbose_name': 'Period', 'verbose_name_plural': 'Periods'},
        ),
        migrations.AlterModelOptions(
            name='periodsummary',
            options={'ordering': ['period', 'summary_code'], 'verbose_name': 'Period Summary', 'verbose_name_plural': 'Period Summaries'},
        ),
        migrations.AlterModelOptions(
            name='postclosingadjustment',
            options={'ordering': ['-adjustment_date', '-id'], 'verbose_name': 'Post Closing Adjustment', 'verbose_name_plural': 'Post Closing Adjustments'},
        ),
        migrations.RenameIndex(
            model_name='closingrun',
            new_name='closing_clo_period__48829e_idx',
            old_name='closing_run_period_status_idx',
        ),
        migrations.RenameIndex(
            model_name='period',
            new_name='closing_per_start_d_2ea1e0_idx',
            old_name='closing_period_dates_idx',
        ),
        migrations.RenameIndex(
            model_name='period',
            new_name='closing_per_status_e98afb_idx',
            old_name='closing_period_status_idx',
        ),
        migrations.RenameIndex(
            model_name='period',
            new_name='closing_per_frequen_056253_idx',
            old_name='closing_period_freq_idx',
        ),
        migrations.RenameIndex(
            model_name='periodsummary',
            new_name='closing_per_period__1d5a84_idx',
            old_name='closing_summary_code_idx',
        ),
        migrations.RenameIndex(
            model_name='postclosingadjustment',
            new_name='closing_pos_related_14f53f_idx',
            old_name='closing_adj_period_idx',
        ),
        migrations.RenameIndex(
            model_name='postclosingadjustment',
            new_name='closing_pos_status_406372_idx',
            old_name='closing_adj_status_idx',
        ),
        migrations.RenameIndex(
            model_name='postclosingadjustment',
            new_name='closing_pos_adjustm_7c3350_idx',
            old_name='closing_adj_date_idx',
        ),
        migrations.AlterField(
            model_name='closingrun',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='period',
            name='frequency',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('semi_annual', 'Semi annual'), ('annual', 'Annual')], default='quarterly', max_length=20),
        ),
        migrations.AlterField(
            model_name='period',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('reopened', 'Reopened')], default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='postclosingadjustment',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
    ]
