# Generated by Django 5.2.17 on 2026-08-20 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closing', '0008_alter_closingrun_options_alter_period_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='periodsummary',
            name='unique_period_summary_code',
        ),
        migrations.AddConstraint(
            model_name='periodsummary',
            constraint=models.UniqueConstraint(fields=('period', 'closing_run', 'summary_code'), name='unique_period_run_summary_code'),
        ),
    ]
