# Generated by Django 5.2.17 on 2026-08-29 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashboxes', '0008_openingbalanceadjustment_and_more'),
        ('master_data', '0001_initial'),
        ('sales', '0007_sync_sales_model_state'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customerledgerentry',
            name='opening_balance_adjustment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_ledger_entries', to='cashboxes.openingbalanceadjustment'),
        ),
        migrations.AddIndex(
            model_name='customerledgerentry',
            index=models.Index(fields=['opening_balance_adjustment'], name='sales_custo_opening_e1f68a_idx'),
        ),
    ]
