# Generated by Django 5.2.17 on 2026-10-08 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0009_salesreturnline_salesreturn_and_more"),
        ("staff", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesinvoice",
            name="salesperson",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sales_invoices",
                to="staff.employee",
            ),
        ),
    ]
